### ISSUE TITLE
Makefile change required

### ISSUE THREAD

**Issue by develone** [Oak-Development-Technologies/RPGA-Feather#1]
git diff Makefile
diff --git a/Makefile b/Makefile
index b5fccda..a455266 100644
--- a/Makefile
+++ b/Makefile
@@ -6,7 +6,7 @@ pcf_file=$(PCF_DIR)/io.pcf
 build:
        yosys -p "synth_ice40 -top top -json $(filename).json" $(filename).v
        nextpnr-ice40 --u4k --package sg48 --json $(filename).json --pcf $(pcf_file) --asc $(filename).asc
-       icepack $(filename).asc ../$(filename).bin
+       icepack $(filename).asc $(filename).bin
 
 clean:
-       rm -rf $(filename).blif $(filename).asc $(filename).bin
\ No newline at end of file
+       rm -rf $(filename).blif $(filename).asc $(filename).bin

make build
7 warnings, 0 errors

Info: Program finished normally.
icepack src/top.asc src/top.bin

**Comment by skerr92** [comment]
Thanks for reporting this, I'll get that fixed up 👍🏻

**Comment by skerr92** [comment]
Alrighty, this issue is fixed and part of main. Let me know if you have any other issues :)
