### ISSUE TITLE
Adding support to your RPGA-Feather (RP2040 + iCE40) FPGA Board to IceStudio (Graphical IDE App)

### ISSUE THREAD

**Issue by benitoss** [Oak-Development-Technologies/RPGA-Feather#2]
I think It will be interesting for the user to expand the possibilities of programming of your RPGA-Feather FPGA Development Board.  

I am so enthusiastic of  Lattice FPGA  boards that I just added more than 5 different boards to the IceStudio App. IceStudio is a free software to easily program the FPGA through graphic blocks.
The IceStudio webpage is here -->  https://icestudio.io/

I have already added different Lattice boards to IceStudio
Colorlight boards --> [FPGAwars/icestudio#500](https://github.com/FPGAwars/icestudio/pull/500)
FleaFPGA-Ohm ECP5 board --> [FPGAwars/icestudio#521](https://github.com/FPGAwars/icestudio/pull/521)
ECP-5 Evaluation Board --> [FPGAwars/icestudio#541](https://github.com/FPGAwars/icestudio/pull/541)
Butterstick r10 & OrangeCrab r2 Boards  --> https://github.com/FPGAwars/icestudio/pull/700

If you desire I can add support of your Mimas FPGA board to the Icestudio Software in a few days. I only need one FPGA Board to test it 
Please tell me if you are interested  

Thanks and regards

Fernando Mosquera
UNT PhD Student in Computer Science and Engineering

**Comment by skerr92** [comment]
There are definitely plans to bring this and another ice40 board to ice studio, I'll let you know when that happens 🤓

**Comment by skerr92** [comment]
PR is up for this board and IcyBlue FPGA. https://github.com/FPGAwars/icestudio/pull/752

**Comment by skerr92** [comment]
Finally merged into apio. I'm going to go ahead and close this issue.
