### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by develone** [Oak-Development-Technologies/RPGA-Feather#3]
Can you add pdf of schematic.

**Comment by skliffmueller** [comment]
This should get you started

[RPGA.pdf](https://github.com/user-attachments/files/16004084/RPGA.pdf)

**Comment by skerr92** [comment]
Thanks @skliffmueller for sharing that PDF, I'll add it and credit you.

**Comment by skerr92** [comment]
Added to the README on the main page of the repo. Thanks!
